CREATE TABLE `sr1`.`default_database`.`adsb` (
  `uuid` VARCHAR(2147483647),
  `ts` VARCHAR(2147483647),
  `adsbnow` VARCHAR(2147483647),
  `alt_baro` INT,
  `alt_geom` INT,
  `baro_rate` INT,
  `category` VARCHAR(2147483647),
  `emergency` VARCHAR(2147483647),
  `flight` VARCHAR(2147483647),
  `gs` DOUBLE,
  `gva` INT,
  `hex` VARCHAR(2147483647),
  `lat` DOUBLE,
  `lon` DOUBLE,
  `mach` DOUBLE,
  `messages` INT,
  `mlat` ARRAY<ROW<> NOT NULL>,
  `nac_p` INT,
  `nac_v` INT,
  `nav_altitude_mcp` INT,
  `nav_heading` DOUBLE,
  `nav_qnh` DOUBLE,
  `nic` INT,
  `nic_baro` INT,
  `rc` INT,
  `rssi` DOUBLE,
  `sda` INT,
  `seen` DOUBLE,
  `seen_post` DOUBLE,
  `sil` INT,
  `sil_type` VARCHAR(2147483647),
  `speed` DOUBLE,
  `squawk` INT,
  `tisb` ARRAY<ROW<> NOT NULL>,
  `track` DOUBLE,
  `version` INT
) COMMENT 'adsb'
WITH (
  'properties.bootstrap.servers' = 'kafka:9092',
  'avro-cloudera.properties.schema.registry.url' = 'http://schema-registry:7788/api/v1',
  'connector' = 'kafka',
  'avro-cloudera.schema-name' = 'adsb',
  'format' = 'avro-cloudera',
  'topic' = 'adsb',
  'scan.startup.mode' = 'latest-offset'
)
